[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc_version = '0.8.23'
optimizer_runs = 20000
fs_permissions = [{ access = "read-write", path = "./script-deploy-data"}]